name = "Ex Ample"
notes = [
    "a note about this contact",
    "another note",
]


[[links]]
value = "https://example.com/"
notes = ["personal website"]

[[links]]
value = "https://github.com/example"
notes = ["GitHub profile"]


[[organizations]]
name = "Employer"
role = "CTO"

[[organizations]]
name = "Project"
role = "Maintainer"


[[addresses.email]]
value = "mail@example.com"
notes = ["note about this email address"]

[[addresses.phone]]
value = "+99 9999 999999"
notes = ["note about this phone number"]

[[addresses.matrix]]
value = "@matrix:example.com"
notes = ["note about this Matrix ID"]


[communication.latest]
to = "2021-02-13"
from = "2021-02-13"


[[communication.planned]]
date = "2021-02-20"
notes = ["note about this planned communication"]

[[communication.planned]]
date = "2021-03-13"
notes = ["note about this planned communication"]
