name = "Ex Ample"

notes = [
    "he's completely fictional, therefore we never met",
    "I'm using him as an example contact to demonstrate the file format",
]


[[links]]
value = "https://example.com/"
notes = ["personal website"]

[[links]]
value = "https://github.com/example"
notes = ["GitHub profile"]


[[organizations]]
name = "Ex Ample's Employer"
role = "CTO"

[[organizations]]
name = "Open Source Project"
role = "Maintainer"


[[addresses.email]]
value = "mail@example.com"
notes = ["personal email"]

[[addresses.phone]]
value = "+99 9999 999999"
notes = ["work phone"]

[[addresses.matrix]]
value = "@matrix:example.com"
notes = ["best way to reach him quickly"]


[communication.latest]
to = "2021-02-13"
from = "2021-02-13"


[[communication.planned]]
date = "2021-02-20"
notes = ["weekly call"]

[[communication.planned]]
date = "2021-03-13"
notes = ["ask how that thing went"]
